# Generated by Django 2.2.5 on 2019-09-11 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20190908_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, validators=[django.core.validators.MaxValueValidator(-7.289515), django.core.validators.MinValueValidator(-11.640186)]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, validators=[django.core.validators.MaxValueValidator(8.575844), django.core.validators.MinValueValidator(4.017699)]),
        ),
    ]
